runtime: php73
env: flex
runtime_config:
  document_root: public

env_variables:
  # Put production environment variables here.
  LOG_LEVEL: debug
  APP_BASE_PATH: /tmp
  APP_NAME: Laravel
  APP_ENV: production
  APP_KEY: base64:M6YdSYX/6Yhajdr/bthufN8TGNaZyJRmci0WL3Tbfbs=
  APP_DEBUG: true
  APP_URL: http://localhost

  LOG_CHANNEL: stack
  LOG_DEPRECATIONS_CHANNEL: null

  DB_CONNECTION: mysql
  DB_HOST: 104.199.112.206
  DB_PORT: 3306
  DB_DATABASE: laravel
  DB_USERNAME: application_install
  DB_PASSWORD: pvaL!^SOH5P6%cex2m!HG&pD

  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  FILESYSTEM_DRIVER: local
  QUEUE_CONNECTION: sync
  SESSION_DRIVER: file
  SESSION_LIFETIME: 120

  MEMCACHED_HOST: 127.0.0.1

  REDIS_HOST: 127.0.0.1
  REDIS_PASSWORD: null
  REDIS_PORT: 6379

  MAIL_MAILER: smtp
  MAIL_HOST: mailhog
  MAIL_PORT: 1025
  MAIL_USERNAME: null
  MAIL_PASSWORD: null
  MAIL_ENCRYPTION: null
  MAIL_FROM_ADDRESS: null
  MAIL_FROM_NAME: "${APP_NAME}"

  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  AWS_DEFAULT_REGION: us-east-1
  AWS_BUCKET: null
  AWS_USE_PATH_STYLE_ENDPOINT: false

  PUSHER_APP_ID: null
  PUSHER_APP_KEY: null
  PUSHER_APP_SECRET: null
  PUSHER_APP_CLUSTER: mt1

  MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
  MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"
